'use strict';

// <generated> -- regenerated by `npm run spackle`; do not edit

var ES5 = require('./es5');
var ES2015 = require('./es2015');
var ES2016 = require('./es2016');
var ES2017 = require('./es2017');
var ES2018 = require('./es2018');
var ES2019 = require('./es2019');
var ES2020 = require('./es2020');
var ES2021 = require('./es2021');
var ES2022 = require('./es2022');
var ES2023 = require('./es2023');
var ES2024 = require('./es2024');
var ES2025 = require('./es2025');

var ES6 = ES2015;
var ES7 = ES2016;

var abs = ES2015.abs;
var AbstractEqualityComparison = ES2015['Abstract Equality Comparison'];
var AbstractRelationalComparison = ES2015['Abstract Relational Comparison'];
var AdvanceStringIndex = ES2015.AdvanceStringIndex;
var ArrayCreate = ES2015.ArrayCreate;
var ArraySetLength = ES2015.ArraySetLength;
var ArraySpeciesCreate = ES2015.ArraySpeciesCreate;
var Call = ES2015.Call;
var Canonicalize = ES2015.Canonicalize;
var CanonicalNumericIndexString = ES2015.CanonicalNumericIndexString;
var CharacterRange = ES2015.CharacterRange;
var CompletePropertyDescriptor = ES2015.CompletePropertyDescriptor;
var CompletionRecord = ES2015.CompletionRecord;
var CreateDataProperty = ES2015.CreateDataProperty;
var CreateDataPropertyOrThrow = ES2015.CreateDataPropertyOrThrow;
var CreateHTML = ES2015.CreateHTML;
var CreateIterResultObject = ES2015.CreateIterResultObject;
var CreateListFromArrayLike = ES2015.CreateListFromArrayLike;
var CreateMethodProperty = ES2015.CreateMethodProperty;
var DateFromTime = ES2015.DateFromTime;
var Day = ES2015.Day;
var DayFromYear = ES2015.DayFromYear;
var DaysInYear = ES2015.DaysInYear;
var DayWithinYear = ES2015.DayWithinYear;
var DefinePropertyOrThrow = ES2015.DefinePropertyOrThrow;
var DeletePropertyOrThrow = ES2015.DeletePropertyOrThrow;
var DetachArrayBuffer = ES2015.DetachArrayBuffer;
var EnumerableOwnNames = ES2015.EnumerableOwnNames;
var floor = ES2015.floor;
var FromPropertyDescriptor = ES2015.FromPropertyDescriptor;
var Get = ES2015.Get;
var GetGlobalObject = ES2015.GetGlobalObject;
var GetIterator = ES2015.GetIterator;
var GetMethod = ES2015.GetMethod;
var GetOwnPropertyKeys = ES2015.GetOwnPropertyKeys;
var GetPrototypeFromConstructor = ES2015.GetPrototypeFromConstructor;
var GetSubstitution = ES2015.GetSubstitution;
var GetV = ES2015.GetV;
var GetValueFromBuffer = ES2015.GetValueFromBuffer;
var HasOwnProperty = ES2015.HasOwnProperty;
var HasProperty = ES2015.HasProperty;
var HourFromTime = ES2015.HourFromTime;
var InLeapYear = ES2015.InLeapYear;
var InstanceofOperator = ES2015.InstanceofOperator;
var IntegerIndexedElementGet = ES2015.IntegerIndexedElementGet;
var IntegerIndexedElementSet = ES2015.IntegerIndexedElementSet;
var InternalizeJSONProperty = ES2015.InternalizeJSONProperty;
var Invoke = ES2015.Invoke;
var IsAccessorDescriptor = ES2015.IsAccessorDescriptor;
var IsArray = ES2015.IsArray;
var IsCallable = ES2015.IsCallable;
var IsCompatiblePropertyDescriptor = ES2015.IsCompatiblePropertyDescriptor;
var IsConcatSpreadable = ES2015.IsConcatSpreadable;
var IsConstructor = ES2015.IsConstructor;
var IsDataDescriptor = ES2015.IsDataDescriptor;
var IsDetachedBuffer = ES2015.IsDetachedBuffer;
var IsExtensible = ES2015.IsExtensible;
var IsGenericDescriptor = ES2015.IsGenericDescriptor;
var IsInteger = ES2015.IsInteger;
var IsPromise = ES2015.IsPromise;
var IsPropertyDescriptor = ES2015.IsPropertyDescriptor;
var IsPropertyKey = ES2015.IsPropertyKey;
var IsRegExp = ES2015.IsRegExp;
var IsWordChar = ES2015.IsWordChar;
var IteratorClose = ES2015.IteratorClose;
var IteratorComplete = ES2015.IteratorComplete;
var IteratorNext = ES2015.IteratorNext;
var IteratorStep = ES2015.IteratorStep;
var IteratorValue = ES2015.IteratorValue;
var MakeDate = ES2015.MakeDate;
var MakeDay = ES2015.MakeDay;
var MakeTime = ES2015.MakeTime;
var max = ES2015.max;
var min = ES2015.min;
var MinFromTime = ES2015.MinFromTime;
var modulo = ES2015.modulo;
var MonthFromTime = ES2015.MonthFromTime;
var msFromTime = ES2015.msFromTime;
var NewPromiseCapability = ES2015.NewPromiseCapability;
var NormalCompletion = ES2015.NormalCompletion;
var ObjectCreate = ES2015.ObjectCreate;
var ObjectDefineProperties = ES2015.ObjectDefineProperties;
var OrdinaryCreateFromConstructor = ES2015.OrdinaryCreateFromConstructor;
var OrdinaryDefineOwnProperty = ES2015.OrdinaryDefineOwnProperty;
var OrdinaryGetOwnProperty = ES2015.OrdinaryGetOwnProperty;
var OrdinaryHasInstance = ES2015.OrdinaryHasInstance;
var OrdinaryHasProperty = ES2015.OrdinaryHasProperty;
var QuoteJSONString = ES2015.QuoteJSONString;
var RegExpCreate = ES2015.RegExpCreate;
var RegExpExec = ES2015.RegExpExec;
var RequireObjectCoercible = ES2015.RequireObjectCoercible;
var SameValue = ES2015.SameValue;
var SameValueZero = ES2015.SameValueZero;
var SecFromTime = ES2015.SecFromTime;
var Set = ES2015.Set;
var SetFunctionName = ES2015.SetFunctionName;
var SetIntegrityLevel = ES2015.SetIntegrityLevel;
var SetValueInBuffer = ES2015.SetValueInBuffer;
var SpeciesConstructor = ES2015.SpeciesConstructor;
var SplitMatch = ES2015.SplitMatch;
var StrictEqualityComparison = ES2015['Strict Equality Comparison'];
var StringCreate = ES2015.StringCreate;
var StringGetIndexProperty = ES2015.StringGetIndexProperty;
var SymbolDescriptiveString = ES2015.SymbolDescriptiveString;
var TestIntegrityLevel = ES2015.TestIntegrityLevel;
var thisBooleanValue = ES2015.thisBooleanValue;
var thisNumberValue = ES2015.thisNumberValue;
var thisStringValue = ES2015.thisStringValue;
var thisTimeValue = ES2015.thisTimeValue;
var TimeClip = ES2015.TimeClip;
var TimeFromYear = ES2015.TimeFromYear;
var TimeWithinDay = ES2015.TimeWithinDay;
var ToBoolean = ES2015.ToBoolean;
var ToDateString = ES2015.ToDateString;
var ToInt16 = ES2015.ToInt16;
var ToInt32 = ES2015.ToInt32;
var ToInt8 = ES2015.ToInt8;
var ToInteger = ES2015.ToInteger;
var ToLength = ES2015.ToLength;
var ToNumber = ES2015.ToNumber;
var ToObject = ES2015.ToObject;
var ToPrimitive = ES2015.ToPrimitive;
var ToPropertyDescriptor = ES2015.ToPropertyDescriptor;
var ToPropertyKey = ES2015.ToPropertyKey;
var ToString = ES2015.ToString;
var ToUint16 = ES2015.ToUint16;
var ToUint32 = ES2015.ToUint32;
var ToUint8 = ES2015.ToUint8;
var ToUint8Clamp = ES2015.ToUint8Clamp;
var Type = ES2015.Type;
var ValidateAndApplyPropertyDescriptor = ES2015.ValidateAndApplyPropertyDescriptor;
var ValidateTypedArray = ES2015.ValidateTypedArray;
var WeekDay = ES2015.WeekDay;
var YearFromTime = ES2015.YearFromTime;

module.exports = {
	ES5: ES5,
	ES2015: ES2015,
	ES6: ES6,
	ES2016: ES2016,
	ES7: ES7,
	ES2017: ES2017,
	ES2018: ES2018,
	ES2019: ES2019,
	ES2020: ES2020,
	ES2021: ES2021,
	ES2022: ES2022,
	ES2023: ES2023,
	ES2024: ES2024,
	ES2025: ES2025,
	abs: abs,
	'Abstract Equality Comparison': AbstractEqualityComparison,
	'Abstract Relational Comparison': AbstractRelationalComparison,
	AdvanceStringIndex: AdvanceStringIndex,
	ArrayCreate: ArrayCreate,
	ArraySetLength: ArraySetLength,
	ArraySpeciesCreate: ArraySpeciesCreate,
	Call: Call,
	Canonicalize: Canonicalize,
	CanonicalNumericIndexString: CanonicalNumericIndexString,
	CharacterRange: CharacterRange,
	CompletePropertyDescriptor: CompletePropertyDescriptor,
	CompletionRecord: CompletionRecord,
	CreateDataProperty: CreateDataProperty,
	CreateDataPropertyOrThrow: CreateDataPropertyOrThrow,
	CreateHTML: CreateHTML,
	CreateIterResultObject: CreateIterResultObject,
	CreateListFromArrayLike: CreateListFromArrayLike,
	CreateMethodProperty: CreateMethodProperty,
	DateFromTime: DateFromTime,
	Day: Day,
	DayFromYear: DayFromYear,
	DaysInYear: DaysInYear,
	DayWithinYear: DayWithinYear,
	DefinePropertyOrThrow: DefinePropertyOrThrow,
	DeletePropertyOrThrow: DeletePropertyOrThrow,
	DetachArrayBuffer: DetachArrayBuffer,
	EnumerableOwnNames: EnumerableOwnNames,
	floor: floor,
	FromPropertyDescriptor: FromPropertyDescriptor,
	Get: Get,
	GetGlobalObject: GetGlobalObject,
	GetIterator: GetIterator,
	GetMethod: GetMethod,
	GetOwnPropertyKeys: GetOwnPropertyKeys,
	GetPrototypeFromConstructor: GetPrototypeFromConstructor,
	GetSubstitution: GetSubstitution,
	GetV: GetV,
	GetValueFromBuffer: GetValueFromBuffer,
	HasOwnProperty: HasOwnProperty,
	HasProperty: HasProperty,
	HourFromTime: HourFromTime,
	InLeapYear: InLeapYear,
	InstanceofOperator: InstanceofOperator,
	IntegerIndexedElementGet: IntegerIndexedElementGet,
	IntegerIndexedElementSet: IntegerIndexedElementSet,
	InternalizeJSONProperty: InternalizeJSONProperty,
	Invoke: Invoke,
	IsAccessorDescriptor: IsAccessorDescriptor,
	IsArray: IsArray,
	IsCallable: IsCallable,
	IsCompatiblePropertyDescriptor: IsCompatiblePropertyDescriptor,
	IsConcatSpreadable: IsConcatSpreadable,
	IsConstructor: IsConstructor,
	IsDataDescriptor: IsDataDescriptor,
	IsDetachedBuffer: IsDetachedBuffer,
	IsExtensible: IsExtensible,
	IsGenericDescriptor: IsGenericDescriptor,
	IsInteger: IsInteger,
	IsPromise: IsPromise,
	IsPropertyDescriptor: IsPropertyDescriptor,
	IsPropertyKey: IsPropertyKey,
	IsRegExp: IsRegExp,
	IsWordChar: IsWordChar,
	IteratorClose: IteratorClose,
	IteratorComplete: IteratorComplete,
	IteratorNext: IteratorNext,
	IteratorStep: IteratorStep,
	IteratorValue: IteratorValue,
	MakeDate: MakeDate,
	MakeDay: MakeDay,
	MakeTime: MakeTime,
	max: max,
	min: min,
	MinFromTime: MinFromTime,
	modulo: modulo,
	MonthFromTime: MonthFromTime,
	msFromTime: msFromTime,
	NewPromiseCapability: NewPromiseCapability,
	NormalCompletion: NormalCompletion,
	ObjectCreate: ObjectCreate,
	ObjectDefineProperties: ObjectDefineProperties,
	OrdinaryCreateFromConstructor: OrdinaryCreateFromConstructor,
	OrdinaryDefineOwnProperty: OrdinaryDefineOwnProperty,
	OrdinaryGetOwnProperty: OrdinaryGetOwnProperty,
	OrdinaryHasInstance: OrdinaryHasInstance,
	OrdinaryHasProperty: OrdinaryHasProperty,
	QuoteJSONString: QuoteJSONString,
	RegExpCreate: RegExpCreate,
	RegExpExec: RegExpExec,
	RequireObjectCoercible: RequireObjectCoercible,
	SameValue: SameValue,
	SameValueZero: SameValueZero,
	SecFromTime: SecFromTime,
	Set: Set,
	SetFunctionName: SetFunctionName,
	SetIntegrityLevel: SetIntegrityLevel,
	SetValueInBuffer: SetValueInBuffer,
	SpeciesConstructor: SpeciesConstructor,
	SplitMatch: SplitMatch,
	'Strict Equality Comparison': StrictEqualityComparison,
	StringCreate: StringCreate,
	StringGetIndexProperty: StringGetIndexProperty,
	SymbolDescriptiveString: SymbolDescriptiveString,
	TestIntegrityLevel: TestIntegrityLevel,
	thisBooleanValue: thisBooleanValue,
	thisNumberValue: thisNumberValue,
	thisStringValue: thisStringValue,
	thisTimeValue: thisTimeValue,
	TimeClip: TimeClip,
	TimeFromYear: TimeFromYear,
	TimeWithinDay: TimeWithinDay,
	ToBoolean: ToBoolean,
	ToDateString: ToDateString,
	ToInt16: ToInt16,
	ToInt32: ToInt32,
	ToInt8: ToInt8,
	ToInteger: ToInteger,
	ToLength: ToLength,
	ToNumber: ToNumber,
	ToObject: ToObject,
	ToPrimitive: ToPrimitive,
	ToPropertyDescriptor: ToPropertyDescriptor,
	ToPropertyKey: ToPropertyKey,
	ToString: ToString,
	ToUint16: ToUint16,
	ToUint32: ToUint32,
	ToUint8: ToUint8,
	ToUint8Clamp: ToUint8Clamp,
	Type: Type,
	ValidateAndApplyPropertyDescriptor: ValidateAndApplyPropertyDescriptor,
	ValidateTypedArray: ValidateTypedArray,
	WeekDay: WeekDay,
	YearFromTime: YearFromTime
};
// </generated>
